### ISSUE TITLE
[FR] Add support for local music files

### ISSUE THREAD

**Issue by wwjCMP** [andrewmcgivery/obsidian-soundscapes#5]
Thank you for developing the plugin and for sharing the music that's perfect for writing. It would be great if you could add support for local music files.

**Comment by Ravenclawer** [comment]
+1 for this. Local video files are also good for the plugin since lots of sound sources are videos

**Comment by Horehu** [comment]
+2 it would be epic to be able to use the songs in my library and get closer and closer to obsidian being a "hub" for all the things one does on the pc.

**Comment by andrewmcgivery** [comment]
Thank you for opening this issue!

It's on my list to explore this! Stay tuned!

**Comment by andrewmcgivery** [comment]
@wwjCMP + @Ravenclawer @Horehu 

I'm starting the prototyping for this feature this week.

Because of the complexity of this feature, I'll want to do some beta testing before this is officially released.

I suspect sometime in the next week or so I'll start having some test builds. Would any of you be able and willing to test it out before it goes prime time? :)

**Comment by Ravenclawer** [comment]
I'm glad to be one of the beta testers. I'm using Obsidain 0.15.3, and windows 11.

**Comment by Horehu** [comment]
Yes, I would love to. I currently use the latest version of obsidian 1.5.3 on windows 11.

**Comment by andrewmcgivery** [comment]
UI is coming along... almost everything is functional... just need to do search and explore shuffle!

Once that is done, I'll have some cleanup and refactoring... and then a bunch of local testing on my own for any regressions... and then should be good for beta! Next week is feeling obtainable at this point. :)

![image](https://github.com/andrewmcgivery/obsidian-soundscapes/assets/4482878/66ddc172-c56c-4927-98c9-fa834d2d8079)

![image](https://github.com/andrewmcgivery/obsidian-soundscapes/assets/4482878/37b44df9-0edf-4f98-b2c8-599731e9f019)

**Comment by andrewmcgivery** [comment]
Getting pretty close!

Search works, updated the settings screen, and did a major refactoring.

Last on the TODO is experiment with shuffle mode... then I'll do a bunch of my own testing... and then I'll work on getting a beta channel setup. :)

![image](https://github.com/andrewmcgivery/obsidian-soundscapes/assets/4482878/3baa6917-9cbf-4645-b56b-0ca3ec485e60)

![image](https://github.com/andrewmcgivery/obsidian-soundscapes/assets/4482878/36d8c70d-715c-4128-8f0a-a325d9747adb)

**Comment by Horehu** [comment]
Great to see how you are progressing, much success 💪, I'm going on vacation for 4 days, when I get back let me know if you still need testers.

**Comment by andrewmcgivery** [comment]
Plugin is now available for beta testing! (Please first read https://github.com/andrewmcgivery/obsidian-soundscapes/releases/tag/1.2.0-beta.1 for notes, warnings, and limitations on this beta release).

To install, you can use the BRAT plugin and point to this repo. (at your own risk of course... this IS a beta!)

Please share here your size of library, OS, etc here... and obviously and feedback!

**Comment by phthallo** [comment]
Love this new addition! Just a couple bits of feedback :) 

**Library Size:** 277 files (all MP3s) 
**OS:** Windows 10
**Obsidian Version:** v.1.5.3

1. **I usually have both sidebars open, which makes some of the text cramped. See the comparison:** 
*full screen* 
![image](https://github.com/andrewmcgivery/obsidian-soundscapes/assets/84078890/7b8dabdc-6d03-452c-83b0-c716b8dc9dc2)
*both sidebars open*
![image](https://github.com/andrewmcgivery/obsidian-soundscapes/assets/84078890/28fbfac6-549d-4e5d-8186-6d118268d9dc)
The only fix I can think of is truncating the text when it becomes too long, and just showing the longer version on hover or something. This would also help if you happened to have a music file with an excessively long name, for whatever reason, so the Soundscapes page does not need to scroll horizontally. 
Making the volume bar responsive too (since it seems to retain its size no matter what) would also help when resizing the screen.

2. **Potentially adding pagination/scrolling for search results, as five is pretty restrictive.** 

3. **Inconsistencies with displaying file extensions**
Not sure why this happens, but it probably has something to do with how it was downloaded (since my files either come from spotDL (doesn't show .mp3), dodgy MP3 converters online (shows .mp3) or official sources (doesn't show .mp3)) Regardless, being able to hide all of the extensions would be great. 
![image](https://github.com/andrewmcgivery/obsidian-soundscapes/assets/84078890/2cc65a18-d616-446e-b901-67f6a36f1d5f) 

4. **Song persistence between restarts of Obsidian**
Right now, the currently playing song defaults back to the first song in the library whenever you restart Obsidian. It'd be great if it could save what song is playing when you quit and keep it on startup. 

5. **Beta exclusive issue** 
Because of how the plugin detects when the [local version is out of date](https://github.com/andrewmcgivery/obsidian-soundscapes/blob/13538409af613703b68f16693af2c88b80f01362/main.ts#L237), using the beta version prompts a "There is an update available" message on startup, which blocks the search bar unless you have the right side bar open/unless you swipe it away manually. This is just something minor though :'D

**Comment by Ravenclawer** [comment]
I'm on Windows 11, obsidian 0.15.3, and the plugin works perfectly. I have 218 musfolderses.
![image](https://github.com/andrewmcgivery/obsidian-soundscapes/assets/73892411/d3a2bab8-783c-47fa-b3f4-babb2bd7b20b) 
1 Maybe you can add a favorite button on the status bar before the music title that adds the current music to a favorite list and allow the music title on the status clickable to hover a small panel to show the favorite music list. 

2 Adding an option to add multiple folders and a button that allows switching between different folders in the status bar. 

Just some arbitrary suggestions, the current plugin is nearly perfect, thank you for putting time into creating this wonderful plugin.

some of my suggestions overlap with https://github.com/andrewmcgivery/obsidian-soundscapes/issues/5#issuecomment-1937372749

**Comment by andrewmcgivery** [comment]
@phthallo Awesome feedback! Most (all?) of this has been incorporated into1.2.0-beta.2 (available now!). Give it a try and let me know what you think. :)

@Ravenclawer Thank you for the feedback and Interesting ideas! Very close to my thoughts on Playlists that are on the backlog to consider post version 1.2.0.

**Comment by phthallo** [comment]
Loving it! Thanks for taking my feedback into account :D Will let you know if I run into any further bugs/issues!

**Comment by andrewmcgivery** [comment]
I did some testing on a mac and have been using it myself passively. If nobody reports any major issues by the weekend, I'll likely be releasing this feature to main. :)

**Comment by andrewmcgivery** [comment]
This is now launched on main! Thanks to everyone who tested! :)
